modules/html/producer/html_producer.cpp
=> Crossdomain calls in 2.0

modules/html/producer/html_producer.cpp
Reverts CasparCG/Server#376
Needs to be managed and tested by core team.
=> Revert "Crossdomain calls in 2.0"

README.txt
Replaced the entire, very old, README in 2.1.0 with an updated version from 2.0.7. 
Changes:
- New initial text at the top
- Spelling mistakes fixed
- Contributor list fixed
- Email addresses slightly obfuscated for rudimentary spam protection
- URLs are checked and working
- Separated Windows and Linux requirements and installation sections
To do:
- Check Windows requirements (Windows 8 and 10 support?)
- Check Windows installation (are the libraries still necessary?)
- Write Linux requirements
- Write Linux installation instructions
=> Readme 2.1.0 update

modules/image/consumer/image_consumer.cpp
Fix thumbnail saving on non-windows systems where function FreeImage_SaveU does nothing.
=> Fix thumbnail saving on non-windows systems

modules/ffmpeg/producer/muxer/frame_muxer.cpp
This addresses the problem I've described in issue #492
=> Increase stream buffer size limit to 120

modules/ffmpeg/producer/input/input.cpp
=> [ffmpeg_producer] Remove unused flags variable in queued_seek

.gitignore, core/producer/frame/basic_frame.cpp, modules/ffmpeg/producer/audio/audio_decoder.cpp, modules/ffmpeg/producer/ffmpeg_producer.cpp, modules/ffmpeg/producer/util/util.cpp, modules/ffmpeg/producer/video/video_decoder.cpp, modules/ffmpeg/producer/video/video_decoder.h, modules/image/consumer/image_consumer.cpp
It's a bit of a hack, but it works...
=> If available use secondary video stream as separate alpha

README
=> [README]  common linux related issues

CMakeModules/LegacyBuild.cmake, accelerator/cpu/image/image_mixer.cpp, build-scripts/windows-vs2015/build.bat, build-scripts/windows-vs2015/set-variables-and-build.bat, common/log.cpp, dependencies64/boost/boost/config/auto_link.hpp
A bunch of issues I encountered when attempting to build via the scripts.
=> Fix building with vs2015

dependencies64/cef/linux/Resources/icudtl.dat, modules/html/CMakeLists.txt
Add missing icudtl.dat for linux
Change CEF related dir variables in CMakeLists.txt
=> [html] Fix building [LFS enabled]

src/CMakeModules/Bootstrap_Windows.cmake, src/modules/html/CMakeLists.txt
=> Fix release build on windows

src/modules/ffmpeg/producer/av_producer.cpp
This is a revised PR based on the latest changes in the 2.2.0 branch. This supersedes https://github.com/CasparCG/server/pull/696
=> check for best videoquality before selecting stream

src/modules/decklink/consumer/decklink_consumer.cpp, src/modules/decklink/producer/decklink_producer.cpp, src/modules/html/CMakeLists.txt
Fixes #825 
Checked that it builds on both windows and linux
=> fix: linux build

src/modules/html/producer/html_producer.cpp
This will make OSC output at least some information about what is currently happening.
=> Store HTML filename in state for OSC

src/modules/decklink/producer/decklink_producer.cpp
=> fix(decklink): guard against null video or audio frame from decklink

src/core/producer/stage.cpp
Highly unlikely to happen, but the risk is there.
I put a sleep for 10s before the call to `other_impl->executor_.invoke` and could very easily produce deadlocks with the following.
```
SWAP 1-10 2-10
SWAP 2-11 1-11
```
=> fix(stage): Potential deadlock when running multiple cross-channel swap commands

src/shell/casparcg.config
this minor thing seems to be gone.
=> Little add-on casparcg.config

src/protocol/util/http_request.cpp
=> fix(amcp) #969 Fails to connect to scanner service without any active network

README.md
Added the solutions to some error messages I got while trying to run on Ubuntu 18.04 to the readme
=> Added error messages and solutions for running on Ubuntu 18.04

src/accelerator/ogl/image/image_kernel.cpp, src/modules/screen/consumer/screen_consumer.cpp
fixes issues caused by 1499d11d90ac8ad3a437bc2ae1746f84e6e33bc9
=> fix: windows build

src/core/producer/layer.cpp
See #1062 for more info. Updated with feedback from review.
=> Add background into state (and move foreground into own object)

BUILDING.md
Added a remark regarding docker with sudo and the file ownership of the copied files.
=> Update BUILDING (linux)

src/accelerator/accelerator.h, src/accelerator/ogl/image/image_kernel.cpp, src/common/log.cpp, src/core/frame/frame_transform.cpp, src/modules/ffmpeg/producer/av_producer.cpp, src/modules/ffmpeg/producer/av_producer.h, src/modules/ffmpeg/util/av_util.h
Fix bugs in the code exposed by the clang compiler on Linux.
Fixes most of #1141.
=> Fix clang build problems.

src/modules/screen/consumer/screen_consumer.cpp
Rewrite of #805 to use the shader introduced in #1040 and multiple draw calls using the same unmodified frame data.
Some work may be needed for stretch modes other than fill as I'm not sure how the segments should align themselves
=> feat(screen): Side by side key

src/modules/oal/consumer/oal_consumer.cpp
=> Fixed memory leak in system audio consumer

src/core/video_channel.cpp
=> Fix build issues due to missing semicolon #1204

src/modules/ffmpeg/producer/av_producer.cpp
Fix for discussion https://github.com/CasparCG/server/pull/1215#discussion_r291501178
=> FFmpeg producer use aresample filter only once

src/modules/ffmpeg/producer/av_producer.cpp
Fixes #874.
The provided files are unusual in that they have a video stream that repeats. These repeated video packets are beyond the reported duration of the file, meaning that to play correctly the producer must be limited by the duration rather than an eof flag from the source.
This change tightens up the time checking to make sure that the producer output stops on the last available frame before the end time calculated from the reported duration. The producer stops two frames earlier than with the current code.
This change will also affect LOADBG and similar when setting a LENGTH parameter.
=> Tighten handling of streams with packets beyond duration

src/core/producer/stage.cpp
Fix #1295 
- Prevents the server from crashing
- Makes sure new calls to these layers work as expected
Creating a circular route leads to frozen video and looped audio (which will likely buzz).
This fix treats this state as a possible intermediate-state that can occur, that the user must be able to proceed from, without adding logic to the protocol level.
=> Add logic to detect circular route setup and skip the recursion

BUILDING.md
Added missing dependencies in the documentation when building the server on a Ubuntu 18.04 target.
=> Added required dependencies for the Ubuntu 18.04 development build.

src/common/os/linux/thread.cpp, src/common/os/thread.h, src/common/os/windows/thread.cpp, src/core/video_channel.cpp, src/modules/decklink/consumer/decklink_consumer.cpp
Currently only done for THREAD_PRIORITY_TIME_CRITICAL which is the
highest (realtime priority class) available on Windows. SCHED_RR
should work for that.
=> Abstract setting thread priorities & implement for linux.

src/modules/newtek/consumer/newtek_ndi_consumer.cpp, src/modules/newtek/interop/Processing.NDI.DynamicLoad.h, src/modules/newtek/interop/Processing.NDI.Find.h, src/modules/newtek/interop/Processing.NDI.FrameSync.h, src/modules/newtek/interop/Processing.NDI.Lib.cplusplus.h, src/modules/newtek/interop/Processing.NDI.Lib.h, src/modules/newtek/interop/Processing.NDI.Recv.ex.h, src/modules/newtek/interop/Processing.NDI.Recv.h, src/modules/newtek/interop/Processing.NDI.Routing.h, src/modules/newtek/interop/Processing.NDI.Send.h, src/modules/newtek/interop/Processing.NDI.compat.h, src/modules/newtek/interop/Processing.NDI.deprecated.h, src/modules/newtek/interop/Processing.NDI.structs.h, src/modules/newtek/interop/Processing.NDI.utilities.h, src/modules/newtek/producer/newtek_ndi_producer.cpp, src/modules/newtek/util/ndi.cpp, src/modules/newtek/util/ndi.h
(NDI 2021-11-03 r127785 v5.0.10)
=> Upgrade to NDI5

CHANGELOG.md
2.3.2 and 2.3.3 changes added to the chnagelog.
=> chore: update changelog for 2.3.2 and 2.3.3

src/modules/bluefish/consumer/bluefish_consumer.cpp
Fix for https://github.com/CasparCG/server/issues/1470
Added praga ignore for warnings with conditional for MSVC
=> fix: Build failure with VS 2022

src/core/producer/route/route_producer.cpp
Signal will eventually fire into route_producer object that is being destroyed causing segmentation fault.
By connecting signal to a weak pointer of route_producer and checking that pointer is still valid this problem is eliminated.
=> fix: race condition when destroying route_producer

src/CMakeLists.txt
This is mainly for poor blokes like me who can't afford a full-blown IDE and use vim instead. I also took the liberty to do a small clean-up of the main CMake file to be conformant to the current syntax.
=> chore: Add support for language servers

src/modules/image/util/image_loader.cpp
=> fix: Respect EXIF rotate flag

src/modules/ffmpeg/util/av_util.cpp
* Addresses issue introduced in 2ffc2024d3ff1fa293f407867c2239ffe06a2b05
* Should fix #1563 and #1542
=> fix: wrong widths in ffmpeg::pixel_format_desc

CHANGELOG.md, _typos.toml, src/CMakeModules/CasparCG_Util.cmake, src/accelerator/ogl/image/image_kernel.cpp, src/common/env.cpp, src/common/memory.h, src/core/diagnostics/osd_graph.cpp, src/modules/bluefish/consumer/bluefish_consumer.cpp, src/modules/bluefish/interop/BlueDriver_p.h, src/modules/bluefish/interop/BlueVelvetCFuncPtr.h, src/modules/bluefish/producer/bluefish_producer.cpp, src/modules/bluefish/util/blue_velvet.cpp, src/modules/decklink/consumer/frame.cpp, src/modules/decklink/linux_interop/DeckLinkAPIConfiguration.h, src/modules/flash/producer/FlashAxContainer.cpp, src/modules/flash/util/swf.cpp, src/modules/image/util/image_algorithms.h, src/protocol/amcp/AMCPCommandQueue.cpp, src/protocol/osc/client.cpp, src/protocol/osc/oscpack/OscReceivedElements.h, src/protocol/util/lock_container.cpp, src/shell/casparcg.config, src/shell/copy_deps.sh, src/shell/windows_specific.cpp, src/tools/bin2c.cpp, tools/update-format.sh
=> fix: Fix typos in comments and strings

src/modules/screen/consumer/screen_consumer.cpp
Adds support for 16bit color depth in screen consumer
=> feat: screen consumer support for 16bit

src/shell/main.cpp
I tried installing the signal handlers directly in main before initialization, but that didnt work with CEF enabled. There's supposed to be a setting to disable cef signal handlers using `settings.disable_signal_handlers` but didn't seem to make any difference. Installing them after everything has been initialized seems to work.
=> fix: exit gracefully on SIGINT and SIGTERM

src/modules/ffmpeg/consumer/ffmpeg_consumer.cpp
There's no need to convert pixel format before we pass frames to ffmpeg, it should handle conversion as necessary. If your output pixel format is not YUVA422 ffmpeg would make an additional conversion. With this change, a single conversion should be possible.
It may have been required at some point to do parallel slices, but that should no longer be necessary as ffmpeg/swscale should be able to do that natively.
=> fix: remove unnecessary sws scale forcing conversion to YUVA422
