- shell/server.cpp
Changed predefined_client to predefined-client to match predefined-clients group name (also in example config file it is predefined-client).
> Fix inconsistent config parameter name

- modules/ffmpeg/producer/util/util.cpp
CasparCG doesn't compile with GCC 5.1.1 and above - problem is related to modules/ffmpeg/producer/util/util.cpp which in function
bool is_valid_file(const std::wstring& filename, bool only_video)
returns nullptr instead of proper bool (false).
Please apply this small fix.
> Fix issue #366 - return false instead of nullptr

- CMakeLists.txt
Compilation in GCC5 fails because of ABI change - I have added _GLIBCXX_USE_CXX11_ABI=0 definition to allow this type of compilation without need to update libraries.
> Fix issue #366 - add _GLIBCXX_USE_CXX11_ABI=0 definition

- modules/ffmpeg/producer/input/input.cpp
This PR fixes the CPU-usage going up when a file has finished playing in the ffmpeg-producer.
Related issue: #461
> Fix CPU hogging on EOF in ffmpeg producer.

- modules/psd/layer.cpp
Fix compilation in GCC 5.3.1 by providing namespace for isnan() function.
> Use namespace for isnan() in PSD module

- modules/ffmpeg/producer/ffmpeg_producer.cpp
This patch adds optional "REL" (relative) and "END" suffixes to the SEEK command to seek from the current position and from the end of the currently playing file.
So, one can do something like this:
`CALL 1-10 SEEK -30 REL`    to jump 30 frames back; or
`CALL 1-10 SEEK  60 REL`    to jump 60 frames forward
This essentially enables scrubbing. I ran the following:
for i in `seq 1 100`; do casparcg-send "CALL 1-10 SEEK 30 REL"; done
for i in `seq 1 100`; do casparcg-send "CALL 1-10 SEEK -30 REL"; done
and I saw that it was good. :)
Additionally, to jump to 30 seconds before the end of the video, one can do:
`CALL 1-10 SEEK 900 END` (assuming 30fps)
This is useful, when doing a run-through of an event and wanting to skip to the end of the video.
> [ffmpeg_producer] Add relative and "from end" seeking

- modules/ffmpeg/producer/ffmpeg_producer.cpp
- modules/ffmpeg/producer/input/input.cpp
- modules/ffmpeg/producer/input/input.h
This patch adds support for the following `PLAY` command syntax:
PLAY 1-10 folder/clip IN 10 LENGTH 50
PLAY 1-10 folder/clip IN 10 OUT 60 (equivalent to the above)
(Use of `SEEK` instead of `IN` is still supported.)
Following `SEEK` command syntax is now supported:
CALL 1-10 SEEK 123 (seek to absolute frame 123)
CALL 1-10 SEEK REL 10 (seek 10 frames forward from current position)
CALL 1-10 SEEK REL -50 (seek 50 frames back from current position)
CALL 1-10 SEEK IN (seek to IN point)
CALL 1-10 SEEK IN 10 (seek to 10 frames after IN point)
CALL 1-10 SEEK IN -50 (seek to 50 frames before IN point)
Additionally, `OUT` and `END` can be specified in place of `IN` to seek relative to the OUT point or the end of the file respectively.
Following `CALL` command syntax is now supported:
CALL 1-10 IN …
> Add support for IN and OUT parameters in PLAY, CALL and SEEK commands

- build-scripts/build-linux.sh
Option "-A x64" throws error:
Generator Unix Makefiles does not support platform specification, but platform x64 was specified.
Removing this option allows mi to run script without problems.
According to docs only "Visual Studio" generator supports this option, so it probably should be removed for "Unix Makefiles" generator.
https://cmake.org/cmake/help/v3.2/manual/cmake.1.html
> Remove platform name from linux build script

- dependencies64/ffmpeg/ffmpeg-build-linux/build-ubuntu.sh
- dependencies64/ffmpeg/ffmpeg-build-linux/build.sh
To fix commit 8fcbd65d178c051bd1ead43be5c746dad84e02b0 and form a base for building the current ffmpeg libs used on ubuntu linux so ffmpeg required changes like extra compile flags for DV/HDV could be added later with more ease and control.
PS: libiec61883 DV/HDV firewire camere support will be added in a new Pull request based using this one as base!
> Fix ffmpeg build dependencies on clean ubuntu desktop amd64 14.04.3 or higher

- dependencies64/ffmpeg/ffmpeg-build-linux/build-ubuntu.sh
- dependencies64/ffmpeg/ffmpeg-build-linux/build.sh
- modules/ffmpeg/producer/ffmpeg_producer.cpp
- modules/ffmpeg/producer/input/input.cpp
Add ffmpeg linux build dependencies and build flag for DV/HDV video devices using iec61883.
Add ffmpeg producer support using the same URL parameter as v4l2 instead use iec61883 and simple usage example.
The old pull request #502 can/will be dropped if this is committed!
> linux DV/HDV video device support

- modules/ffmpeg/producer/util/util.cpp
This is a pull request for adding a possibility to play MPEG-2 (*.ts) files from media folder.
I have tested some files with the commands used to manage these files (LOADBG, PLAY etc.), everything looks working fine.
> Add *.ts extension to media whitelist

- common/os/linux/prec_timer.cpp
- common/os/windows/prec_timer.cpp
- common/prec_timer.h
Fixes issue #623.
Here's a detailed list of changes:
- Switched to boost high_resolution_clock in the Windows implementation of prec_timer.
- Changed tick_millis to tick_nanos, which accepts nanoseconds instad of milliseconds.
- Changed time_ in prec_timer.h from an unsigned long to a 64-bit int, because an unsigned long is only guaranteed to be a 32-bit int, which is too small to contain nanoseconds since UNIX epoch. I guess it must have already been compiling to a 64-bit integer on Linux, though.
- ~Increased minimum remaining time to perform a Sleep(1) from 2 ms to 20 ms on Windows, because Sleep(1) may sleep for up to 16 ms. An alternative fix could have been to call [timeBeginPeriod](https://msdn.microsoft.com/en-us/library/windows/desktop/dd757624(v=vs.85).aspx) during …
> Fix #623 (prec_timer running fast) by increasing prec_timer resolution

- modules/image/consumer/image_consumer.cpp
- modules/image/util/image_algorithms.h
Fixes #648
https://drive.google.com/open?id=1huOSoaoawhlPin_D_gtlac-_LMu5Qlvt
> [image_consumer] Un-multiply frame colours before writing png to file

- shell/server.cpp
Fixes #634 where a vague exception is thrown if the address is not a valid ipv4 address.
Example config:
```
[2017-11-06 20:56:59.299] [10396] [info]       <osc>
[2017-11-06 20:56:59.299] [10396] [info]          <default-port>6250</default-port>
[2017-11-06 20:56:59.299] [10396] [info]          <predefined-clients>
[2017-11-06 20:56:59.299] [10396] [info]             <predefined-client>
[2017-11-06 20:56:59.299] [10396] [info]                <address>10.42.13.110</address>
[2017-11-06 20:56:59.299] [10396] [info]                <port>5253</port>
[2017-11-06 20:56:59.299] [10396] [info]             </predefined-client>
[2017-11-06 20:56:59.299] [10396] [info]             <predefined-client>
[2017-11-06 20:56:59.299] [10396] [info]                <address>127.0.0.1</address>
[2017-11-06 …
```
> Safely parse predefined OSC addresses

- core/producer/separated/separated_producer.cpp
- core/producer/transition/transition_producer.cpp
Changes to info() in separated and transition producers to make the output of "info #" the same as in 2.0.7, the main reason Is to bring it in line, and to make justmacros and a couple of other tools I use work correctly.
The original differences are below, 2.1 is missing key/fill info and transition-producer info
here are the original differences
2.0
```
<channel>
<video-mode>PAL</video-mode>
<stage>
<layers>
<layer>
<status>playing</status>
<auto_delta>0</auto_delta>
<frame-number>52</frame-number>
<nb_frames>260</nb_frames>
<frames-left>208</frames-left>
<frame-age>44</frame-age>
<foreground>
<producer>
<type>separated-producer</type>
<fill>
<producer>
<type>ffmpeg-producer</type>
<filename>media\CG1080i50.mp4</filename>
<width>1920</width>
<height>1080</height> …
```
> Changes to info() to make 2.1.0 the same as 2.0.7

- accelerator/CMakeLists.txt
- accelerator/accelerator.cpp
- accelerator/cpu/image/image_mixer.cpp
- accelerator/cpu/util/xmm.h
Speeds up the CPU mixer significantly when using GCC. Rebased on top of @Julusian's patch to enable the CPU mixer for Linux.
> GCC optimizations for the CPU mixer

- modules/image/util/image_loader.cpp
> [image_producer] Correctly apply alpha to base64 encoded pngs from AMCP

- protocol/amcp/AMCPCommandsImpl.cpp
- protocol/amcp/AMCPProtocolStrategy.cpp
- protocol/util/AsyncEventServer.cpp
- protocol/util/ClientInfo.h
- protocol/util/protocol_strategy.h
- protocol/util/strategy_adapters.cpp
#640
Rebase of #667 for 2.2.0
Sending a PING to the server causes it to respond with PONG. Additional tokens can be added which will be returned with the PONG.
This command does not support the REQ/RES syntax as in order for it to be excluded from the logs the command has to be filtered out before that handling is applied.
> AMCP PING command

- modules/bluefish/producer/bluefish_producer.cpp
- shell/casparcg.config
- Fix bug in audio decoding, where only 2 channels of audio was ever being decoded.
- change default layout  from 2 channel ( stereo) to 8 channel.
> Bug fix and improvements to how audio is handled by bluefish producer

- CHANGELOG.md
Means it can be easily read on github. eg 
https://github.com/Julusian/CasparCG-Server/blob/patch-1/CHANGELOG.md vs https://github.com/CasparCG/server/blob/2.2.0/CHANGELOG.md
> Reformat changelog to use markdown

- modules/bluefish/consumer/bluefish_consumer.cpp
- shell/casparcg.config
Add support for an application level watchdog, that talks to the bluefish device driver and can enable bypass relays if the application ( casparCG) crashes,
Watchdog only works on the first sdi- stream.  
watchdog is enabled by default, but can be disabled by setting a value of in the config file for the given channel.
> Add support for Hw/ application watchdog to Bluefish consumer

- .editorconfig
- src/modules/html/producer/html_producer.cpp
This is currently not working because the graph sink is being created within a CEF context. I've fixed this by creating the sink while still in a Caspar context and then passing it.
This fixes the issue that the DIAG window wouldn't show the channel and layer where it's playing
> Make sure DIAG window shows play channel and layer of HTML producer

- src/shell/main.cpp
- src/shell/windows_specific.cpp
Fixes termination on Ctrl+C pressed in console window (Ctrl+Break remains working)
Re-posted #317 (sorry for delay)
> Fixes termination on Ctrl+C pressed in console window

- src/modules/ffmpeg/producer/av_input.cpp
> Explicitly check if filename starts with http or https before setting related flags

- .github/issue_template.md
More and more issues are reported and sometimes crucial information is missing already from the begining of the issue. By adding this template and asking for information when creating an issue will increaee the quality of issues. It will also minimize the time to give feedback on a certain issue.
> docs: Improve issue reports upon creation for easier handling

- src/modules/decklink/producer/decklink_producer.cpp
Current versions did not compile on linux due to a type mismatch. I don't have a windows installation so I haven't checked compilaton there, but I can't imagine it would go wrong.
> fix(decklink_producer): build on linux

- src/shell/server.cpp
Now Caspar ends with exception when there is no consumers tag on channel.
> Config: allow channel with no consumers tag

- src/CMakeModules/Bootstrap_Windows.cmake
Solves the issue with invalid CASPAR_REV and CASPAR_HASH fields in version.h when building from zip (no .git folder present)
With this I can now build from zip following the instructions in BUILDING.md, skipping just the git clone step.
#828
> fix: Building from zip on Windows

- src/modules/ffmpeg/producer/ffmpeg_producer.cpp
- src/modules/html/producer/html_producer.cpp
This PR does a few things:
* Checks if the filename contains '.html' in the ffmpeg producer. And if so, returns an empty frame producer.
* Checks if the ffmpeg producer could be created and if not, returns an empty frame producer (currently it will swallow the request and if it fails, it stops. This gives other producers no change to handle the files)
* Removes the [HTML] prefix from the HTML producer. The HTML producer tries to handle input after the ffmpeg producer, so all HLS/DASH and other HTTP-like streams will be handled by ffmpeg in the first place. Because of the previous point, all other items that ffmpeg can't handle will then be passed to subsequent producers (including the HTML producer) and thus, the [HTML] prefix is unneccesary.
What I've tested:
* Normal file (PLAY 1-1 AMB) …
> Don't let ffmpeg handle .html files

- src/CMakeModules/Bootstrap_Windows.cmake
- src/modules/image/CMakeLists.txt
- src/modules/image/packages.config
Fixes #926 
I had to make my own nuget package for this.
Build scripts with instructions: https://github.com/Julusian/nuget-freeimage
@dotarmin do you want to transfer that repo to the caspar org?
If you create a casparcg nuget user, I can make you an owner of the nuget package too.
Alternatively, if it is too much work to maintain a nuget package, this could be put back into git as it is small enough and new versions arent released very often.
> Build freeimage against vs2015

- src/accelerator/ogl/util/device.cpp
- src/common/gl/gl_check.cpp
The version number string had not been built before it was being written to the log.
When an OpenGL exception was thrown, the error code was being turned into a string with the memory address being printed instead of the string
> Fix some opengl logging

- .clang-format
Fixes #822 
> Specifically, we ship version 5.0 of the clang-format.exe.
I had to comment out these lines for it to be accepted due to the version of clang-format being used, but then it just works.
The one requirement I found was that the VS solution has to be located inside the git tree, which it will be if following BUILDING.md
> Make clang-format work with Visual Studio

- src/modules/ffmpeg/producer/av_producer.cpp
I haven't tested it, but this makes the prev_frame code be consistent with next_frame so I am confident it will fix the issue.
> Fix osc total-time when paused #945

- src/modules/bluefish/CMakeLists.txt
- src/modules/bluefish/bluefish.cpp
- src/modules/bluefish/producer/bluefish_producer.cpp
- src/modules/bluefish/producer/bluefish_producer.h
- src/modules/bluefish/util/blue_velvet.cpp
- src/modules/bluefish/util/blue_velvet.h
- src/modules/bluefish/util/memory.h
- add support for bluefish consumer, including new files
producer\
bluefish_producer.h
bluefish_producer.cpp
- add alignment to the way we allocate memory for bluefish DMA objects (memory.h)
- new helper functions in bvc_wrapper class.
- fixed some minor bugs in bvc_wrapper
> Add support for bluefish producer

- src/shell/main.cpp
With this I now get the following on linux when the config file doesn't exist
```
/home/julus/Projects/ccg22/src/cmake-build-debug/staging/bin/casparcg ../casparcg.config
Type "q" to close application.
[2018-04-14 01:02:31.263] [error]    ### Invalid configuration file. ###
[2018-04-14 01:02:31.263] [fatal]   At ../casparcg.config:0: read error. Please check the configuration file (../casparcg.config) for errors.
Process finished with exit code 0
```
> fix: #917 Initialize cout logger before loading config file

- src/CMakeModules/Bootstrap_Windows.cmake
Fixes #955
@dotarmin The build server scripts will need checking to ensure they copy this folder across too
> fix(html) #955 WebM video doesn't play without GPU enabled

- src/protocol/amcp/AMCPCommandQueue.cpp
- src/protocol/amcp/AMCPCommandsImpl.cpp
When `AMCP Command Queue Overflow. Failed to execute command:` was logged, the command was still being queued and eventually executed.
At one point I ended up with over 70000 commands in the queue.
Also the error message sent to the client has been changed to indicate the cause of the failure, which will allow the client to try executing at another time
> fix(amcp) Command queue overflow guard has no effect

- src/accelerator/ogl/image/image_kernel.cpp
- src/accelerator/ogl/image/image_shader.cpp
- src/core/frame/geometry.cpp
- src/core/frame/geometry.h
Fixes #989 & fixes #999 
The key issue was no offset being passed in for the texture buffer data, so it was using the same coordinates as the vertex.
I have tested each of FILL, ROTATE and DISTORT individually and combined and in my testing they now behave the same as 2.1
> fix(opengl) #989 #999 Fix transform, rotate and distort

- src/modules/html/producer/html_producer.cpp
> fix(html) #991 Make url/filename validation less strict when using [HTML] prefix on a play command

- src/modules/screen/consumer/screen_consumer.cpp
Fixes #626
It was expected that the first parameter to the consumer is always the screen index. 
2.0 did not make that assumption
> fix(screen) ADD X-Y SCREEN BORDERLESS

- src/protocol/amcp/AMCPCommandQueue.cpp
- src/protocol/amcp/AMCPCommandsImpl.cpp
- src/protocol/util/http_request.cpp
This cleans up the log when the media-scanner is not running and the relevant commands are used. It should now be more obvious to end users what is happening and hopefully reduce the number of issues and forum topics raised.
```
[2018-06-05 19:25:47.332] [info]    Received message from 127.0.0.1: CLS\r\n
[2018-06-05 19:25:49.353] [error]   Failed to connect to media-scanner. Is it running?
[2018-06-05 19:25:49.353] [error]   Reason: No connection could be made because the target machine actively refused it
[2018-06-05 19:25:49.358] [error]   Failed to execute command: CLS. Turn on log level debug for stacktrace.
[2018-06-05 19:25:49.358] [info]    Sent message to 127.0.0.1:501 CLS FAILED\r\n
```
The full stacktrace is still printed under trace logging.
> fix(media-scanner): don't print stack trace if connection fails

- src/core/frame/frame_transform.cpp
- src/core/frame/frame_transform.h
- src/core/producer/stage.cpp
Fixes #879 
Tested with FILL and OPACITY after CLEAR 1 and at startup.
I'm not 100% certain this is the best solution, but I think this is the better of the two solutions I came up with.
> fix(mixer) tweens dont run on uninitialized layers

- src/modules/screen/CMakeLists.txt
- src/modules/screen/consumer/screen_consumer.cpp
- src/modules/screen/util/x11_util.cpp
- src/modules/screen/util/x11_util.h
- src/shell/casparcg.config
fixes #115 #487 #995
This allows specifying x,y,width,height and always-on-top for a screen consumer.
x and y are an offset relative to the screen selected via screen-index
width and height override the channel format if set. If only one of them is set then the aspect_ratio property is respected to calculate the window size.
These coordinates and dimensions only have effect when the consumer is windowed
Additionally, the aspect_ratio and stretch properties were broken by #966 and now work again.
Some linux window managers were always maximising any screen consumer windows due to them being created at screen size, then the size changed to be correct. It is now set correct when created 
Tested on debian 10 (gnome 3) with intel gpu and on windows 10 with intel gpu
One quirks that I shall …
> feat(screen): Optionally specify absolute coordinates and size of windows

- src/shell/main.cpp
Since the forum is removed, the error message on an unhandled exception should point to github issues.
> fix: error message should point to github

- src/common/log.cpp
- src/common/log.h
- src/protocol/amcp/AMCPCommandsImpl.cpp
- src/shell/main.cpp
fixes #1031 
Also ensures log-level is set to info if the value specified in the config is invalid, and reports that the invalid value was rejected
> fix(amcp): log level validation. add missing get command

- src/accelerator/ogl/image/image_kernel.cpp
- src/accelerator/ogl/util/shader.h
- src/modules/screen/CMakeLists.txt
- src/modules/screen/consumer/screen_consumer.cpp
- src/modules/screen/consumer/screen_shader.cpp
- src/modules/screen/consumer/screen_shader.h
Primarily this avoids the aligned_memshfl() when set to key-only.
It also allows #805 and #1032 to be done more cleanly without any more work on the cpu
> feat(screen): Use shader for screen consumer, to allow gpu to perform key-only step

- src/common/diagnostics/graph.h
- src/modules/html/producer/html_producer.cpp
Small improvement on #854, to avoid the late-frame reports being logged to the console or file, but remain in the diag window
> fix(html): Dont report late-frame from html producer to log

- src/core/producer/layer.cpp
By running
```
PLAY 1-10 amb
LOADBG 1-10 green
```
amb is incorrectly paused by the LOADBG command
> fix: LOADBG pauses currently playing clip

- src/core/monitor/monitor.h
@ronag any idea why it builds without this only on windows?
> fix(build): Linux fails on boost::lexical_cast not being defined in monitor.h

- src/CMakeModules/Bootstrap_Linux.cmake
Remove the 'EXACT' statement to get cmake to accept also 1.67 and
newer.  This allow the code to be build on Debian, with boost 1.67.
> Adjust cmake rules to allow boost 1.66 and newer.

- src/packages/openal/include/AL/alext.h
The copyright statement in b/src/packages/openal/include/AL/alext.h
include the old postal address to FSF.  Replace text with the one
currently recommended by FSF.
> Remove obsolete FSF postal addresse from source header

- src/protocol/amcp/AMCPCommandsImpl.cpp
See #1062 for more info.
> Number-only nodes are not allowed in the XML spec so the INFO-command is currently breaking some XML-parsers. I've changed this so that the preceding name will be appended to the number. For example <0></0> will now be <layer_0></layer_0>
The regex looks for `.name.<digit>.` and replaces it with `.name.name_<digit>.`. This makes the INFO output valid XML.
> Append preceding nodes name to digit-only nodes

- src/accelerator/ogl/image/image_kernel.cpp
- src/accelerator/ogl/image/image_shader.cpp
- src/core/CMakeLists.txt
- src/core/frame/frame_transform.cpp
- src/core/frame/frame_transform.h
- src/core/producer/color/color_producer.cpp
- src/core/producer/frame_producer.h
- src/core/producer/layer.cpp
- src/core/producer/layer.h
- src/core/producer/stage.cpp
- src/core/producer/stage.h
- src/core/producer/transition/sting_producer.cpp
- src/core/producer/transition/sting_producer.h
- src/core/producer/transition/transition_producer.cpp
- src/protocol/amcp/AMCPCommandsImpl.cpp
This allows for doing more complex transitions than are currently supported.
It uses a video file as the mask (it will work with other producers if they report a length)
And another optional video file (or any producer) as the overlay artwork.
The length is dictated by the mask file, if the overlay is longer it will get cut off.
There is an optional parameter to delay the start of the destination producer. 
Example usage:
```
PLAY 1-10 AMB STING wipe_mask 0 wipe_overlay
explanation: 
STING (mask_filename) (dest_start_delay) (overlay_filename)
```
Here is not great looking demo of it in action, along with the source assets. Hopefully this will help others understand how it all fits together when used.
Demo: https://drive.google.com/open?id=1XDuZXug2kepzFLK9MGWdAeNsEKTTv6pM
Assets: …
> feat: Sting transition #1008

- src/core/mixer/mixer.cpp
- src/core/mixer/mixer.h
- src/core/producer/frame_producer.cpp
- src/core/producer/frame_producer.h
- src/core/producer/layer.cpp
- src/core/producer/layer.h
- src/core/producer/route/route_producer.cpp
- src/core/producer/separated/separated_producer.cpp
- src/core/producer/stage.cpp
- src/core/producer/stage.h
- src/core/producer/transition/sting_producer.cpp
- src/core/producer/transition/transition_producer.cpp
- src/core/video_channel.cpp
- src/core/video_channel.h
- src/modules/decklink/producer/decklink_producer.cpp
- src/modules/ffmpeg/producer/av_producer.cpp
- src/modules/html/producer/html_producer.cpp
- src/modules/image/producer/image_producer.cpp
- src/protocol/osc/client.cpp
```
PLAY 2-10 route://1-10 BACKGROUND
PLAY 2-10 route://1-10 NEXT
```
This allows you to view the first frame of the background producer. Intended as a preview of the source to make it possible to visibly show to users that the clip is loaded and it is the correct clip.
BACKGROUND mode will only ever show the first frame of the layer background producer,
NEXT mode will show the first frame of the background clip if one is loaded, otherwise will show the foreground. So if you LOADBG then PLAY, the clip will continue playing.
@ronag I have tried to avoid calling receive on the background producers as much as possible, to avoid adding additional cpu usage for who doesn't use this feature. It would be a bit cleaner to always generate them though.
This also fixes a bug where CLEARing a layer …
> #1007 feat(route) route first frame of layer background producer

- src/modules/bluefish/producer/bluefish_producer.cpp
There is an intermittent issue where the producer sometimes start capturing on the wrong field, when capturing interlaced signals.
this fix solves this problem
> Update bluefish producer.cpp - further improvement of interlaced capture

- src/modules/screen/consumer/screen_consumer.cpp
- src/modules/screen/consumer/screen_shader.cpp
- src/shell/casparcg.config
Related issue #1032.
Test build - https://1drv.ms/u/s!AsCJ7q9Sqbclk4oEa9M6zoJrtAbPIg
Example config:
```
<channel>
<video-mode>1080i5000</video-mode>
<consumers>
<screen>
<datavideo-colors>1</datavideo-colors>
<device>2</device>
<aspect-ratio>16:9</aspect-ratio>
<stretch>none</stretch>
<windowed>true</windowed>
<vsync>true</vsync>
<borderless>true</borderless>
<interactive>false</interactive>
<always-on-top>true</always-on-top>
<x>0</x>
<y>0</y>
</screen> 
</consumers>
</channel>
```
> Added support for DataVideo TC-100/TC-200 Character Generators

- src/shell/main.cpp
Fixing bug in Boost library - https://www.bountysource.com/issues/32827214-boost-filesystem-canonical-enters-infinite-loop-when-current-path-is-a-directory-symlink-on-windows
> Fix boost::filesystem:canonical symlink bug (infinity loop) in Windows

- src/CMakeModules/Bootstrap_Windows.cmake
- src/modules/bluefish/packages.config
- src/modules/decklink/packages.config
- src/modules/ffmpeg/packages.config
- src/modules/oal/packages.config
Updated to stable FFMPEG release (21.02.2019)
> Updated FFMPEG to 4.1.1 (Windows)

- src/accelerator/CMakeLists.txt
- src/accelerator/ogl/image/image_shader.cpp
- src/modules/screen/CMakeLists.txt
- src/modules/screen/consumer/screen_consumer.cpp
- src/tools/bin2c.cpp
Added bin2c arguments validation and ingoring carret return when shader convertion to C header.
Fixed windows build after #1182
> Ingoring carret return when shader convertion to C header.

- src/tools/bin2c.cpp
If you try and build Caspar in Docker (using ```./tools/linux/build-in-docker```) it currently crashes out with the error:
```
/source/tools/bin2c.cpp: In function 'int main(int, char**)':
/source/tools/bin2c.cpp:15:62: error: 'errno' was not declared in this scope
fprintf(stderr, "Error opening file: %s\n", strerror(errno));
^~~~~
/source/tools/bin2c.cpp:15:62: note: suggested alternative: 'perror'
fprintf(stderr, "Error opening file: %s\n", strerror(errno));
^~~~~
perror
tools/CMakeFiles/bin2c.dir/build.make:62: recipe for target 'tools/CMakeFiles/bin2c.dir/bin2c.cpp.o' failed
make[2]: *** [tools/CMakeFiles/bin2c.dir/bin2c.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'tools/CMakeFiles/bin2c.dir/all' failed
make[1]: *** [tools/CMakeFiles/bin2c.dir/all] Error 2
```
This adds …
> Add missing standard library include

- src/core/mixer/audio/audio_mixer.cpp
- src/core/video_channel.cpp
Modified audio mixer to prevent asynchronous audio cadences from causing crackling, and modified video_channel to actually use the cadence instead of the first element of the cadence array.
With regard to issues #838 #1145
> NTSC Audio Fix

- src/modules/ffmpeg/producer/av_producer.cpp
Fixes audio out of sync when source is not in 48kHz sample rate.
Fixes: https://github.com/CasparCG/server/issues/1194 https://github.com/CasparCG/server/issues/1170
> FFmpeg producer allways resample to 48kHz

- src/modules/ffmpeg/producer/av_producer.cpp
fixes #1114  not working with video track shorter then audio track(s) without changing behavior regarding duration selection
> Keep increasing frame time until we hit input_duration_ when we play out still frames;

- src/modules/decklink/consumer/decklink_consumer.cpp
The mixer runs with progressive frames even when the channel is set to be interlaced (eg 50 fps for a 50i channel). The current code pulls two frames from the channel at output 'frame' rate (eg 25 fps) which has an impact on the processing occurring upstream.
This change updates Decklink consumer to add a delay before pulling the second frame from the mixer. It uses the same approach as #1228 but with some changes which include addressing Julian's concerns expressed in that issue:
1. The second field delay time is reduced proportionally if the tick-time is extended to allow the decklink consumer to catch up
2. There is an extra line in the graph to show the field 2 tick time
3. The video and audio copies are now done per field to smooth the impact on the CPU
> Add field delay to decklink consumer in interlace mode to smooth impact on channel

- src/modules/ffmpeg/producer/av_producer.cpp
The audio resample filter takes a parameter for the first pts. This was being calculated with the wrong timebase leading to the outputs being out of sync.
> Fixes #1239. Fix audio filter spec for resample when sample rates are different

- src/modules/decklink/producer/decklink_producer.cpp
When a layer is not playing the last_frame() function is called. This change implements last_frame() for the decklink producer to deliver the most recent buffered frame.
The frame is delivered with the audio volume set to 0 so that no audio will be heard.
The behaviour during pause is the same as for load - the producer will continue to deliver frames.
> #1055 Decklink producer should deliver frames on LOAD

- src/modules/decklink/producer/decklink_producer.cpp
Comparing V2.1 and V2.2 decklink producers there is a lot more CPU processing required by FFmpeg filters in V2.2. Interlaced sources are now always deinterlaced but in addition there are colorspace and fps filters added. In addition the filter output pixel format is set to BGRA which requires a CPU-based color conversion when this conversion is available on the GPU as part of the mixer.
This pull request optimises these extra filters to reduce CPU load as follows:
1. Filter output pixel format is now YUV422P
2. Remove the _colorspace_ filter - now done by the mixer input processing
3. Only insert the _fps_ filter if the decklink framerate doesn't match the channel
4. Use a lower quality deinterlace if using an interlaced input to a channel set to an interlaced format
Early testing showed …
> Optimise decklink producer video filtering

- src/core/producer/route/route_producer.cpp
- src/core/producer/route/route_producer.h
- src/core/producer/stage.cpp
- src/core/producer/stage.h
- src/core/video_channel.cpp
Adds logic to the stage processing to re-order the pulls from producers so that sources get pulled before the routes they support.
This provides zero delay routes within a channel. When a route is from a different channel the delay will be 1 frame.
> feat: zero delay routes

- src/modules/ffmpeg/producer/av_producer.cpp
FFmpeg decoding was set to use 4 threads by default. This change checks the codec capabilities and sets the default number of threads to auto if supported or the detected number of cores if codec threading is supported. Configuration parameter _ffmpeg/producer/threads_ will override this value.
> Fix #1281 Change decoding number of threads default value

- src/modules/flash/producer/flash_producer.cpp
This will fix https://github.com/CasparCG/server/issues/1352 
Part of the flash eol workflow allows the loading of white listed urls.
System paths cannot be white listed so this PR causes the system path to be converted to a URL.
This should ideally be retrospectively fitted to 2.3, 2.0 and other versions in active use.
> Cause flash files to be loaded by url

- src/modules/ffmpeg/producer/av_producer.cpp
- src/modules/ffmpeg/producer/av_producer.h
- src/modules/ffmpeg/producer/ffmpeg_producer.cpp
Not sure why we have the image producer nor why it has lower prio than the html producer. 
Use ffmpeg producer for common image formats so that they can be loaded over http.
Fixes: https://github.com/CasparCG/server/issues/1366
> ffmpeg producer seekable + images

- src/core/producer/layer.cpp
- src/core/producer/layer.h
- src/core/producer/stage.cpp
- src/core/producer/stage.h
- src/protocol/amcp/AMCPCommandsImpl.cpp
Adds two features:
- Adds `CLEAR_ON_404` parameter to LOAD/LOADBG/PLAY commands, which results in loading an empty producer in case the command ends with 404
- `LOAD` command with no parameters puts the background clip in the 'preview' state, as if `LOAD` with that clip was done
> feat: CLEAR_ON_404 param and LOAD without params

- src/modules/ffmpeg/producer/av_producer.cpp
> ffmpeg producer: Make decoder wait for capacity.

- src/accelerator/ogl/image/shader.frag
`texture2D` has been deprecated since OpenGL 3.0 and isn't supported by
recent Mesa versions on Linux (tested with Mesa 21.3.6 on AMD RX 6800
XT).
> fix: Replace deprecated texture2D GLSL function

- src/CMakeModules/FindTBB.cmake
The version detection fails with TBB 2021.1 or later due to header file
changes. Since the the version number isn't actually used anywhere, it
seems easier to remove this code rather than try to maintain
compatibility with different TBB versions.
> cmake: Fix compatibility with TBB >= 2021.1

- src/common/except.h
- src/common/log.cpp
This fixes a couple of compatibility issues when compiling with newer boost versions (tested on 1.76.0). This doesn't change the default boost version, nor should it affect compatibility with older boost versions.
> Fix compiling with newer versions of boost

- src/shell/main.cpp
When CasparCG is started under SystemD in linux
stdin is closed and will always return EOF.
This results in an endless loop in the read thread.
Instead, when EOF is encountered, break out of the loop.
> Fix endless looping on stdin in Linux

- src/CMakeModules/FindFFmpeg.cmake
It seems like the prefix passed into `pkg_check_modules` is a mistake:
later calls expect `PC_LIB${_component}_*` to be set by
`pkg_check_modules`, not `${_component}_*`
Before this change, pkg_check_modules would set the
`${_component}_INCLUDE_DIRS` variable. The later call to `find_path`
also expects to set this variable, but doesn't if it has already been
set. On some systems, (e.g. Arch Linux), `pkg_check_modules` sets this
variable to an empty string as the header files are in the default
include directory. Since `find_path` won't overwrite the variable with
the correct value, it will appear like the include directories weren't
found, even if they do exist.
> fix: incorrect variable name in FindFFmpeg

- src/core/producer/transition/sting_producer.cpp
- src/core/producer/transition/sting_producer.h
- src/protocol/CMakeLists.txt
- src/protocol/amcp/amcp_args.cpp
- src/protocol/amcp/amcp_args.h
- src/protocol/util/tokenize.cpp
This adds a new AMCP syntax, solely used by the STING transition for now, to define key&value pairs rather than relying on parameter order, or special keywords that are not guaranteed to be unique. eg `STING (MASK=wipe_mask OVERLAY=wipe_over TRIGGER_POINT=0)
Additionally, it adds 2 more parameters to the sting transition to define when/how the audio should fade.
> feat: sting transition audio fade

- src/modules/ffmpeg/producer/av_producer.cpp
- src/modules/ffmpeg/producer/av_producer.h
- src/modules/ffmpeg/producer/ffmpeg_producer.cpp
Allow both SEEK and IN to be defined for ffmpeg PLAY commands.
Allows for looping between 2 points, and starting at a different point.
> feat(ffmpeg): Allow specifying both SEEK and IN during PLAY commands

- src/modules/decklink/producer/decklink_producer.cpp
- src/modules/ffmpeg/consumer/ffmpeg_consumer.cpp
- src/modules/ffmpeg/ffmpeg.cpp
- src/modules/ffmpeg/producer/av_input.cpp
- src/modules/ffmpeg/producer/av_producer.cpp
- src/modules/ffmpeg/util/av_util.cpp
See individual commits for what each change is.
The final commit does effectively revert 7ac31ee94f810a41c931e2000f11c874b7da7930 for ffmpeg >= 5.0. I'm not sure exactly what this is doing or why it's necessary, but it doesn't seem to be possible anymore in ffmpeg 5.0. I don't know if there's another way of doing something equivalent. I've added a condition to keep the old behaviour on ffmpeg 4.x, but this doesn't seem like a very good long-term solution, so any suggestions here are appreciated.
None of these changes should affect behaviour on ffmpeg 4.x.
> fix: compatibility with ffmpeg 5.0

- src/modules/ffmpeg/producer/ffmpeg_producer.cpp
Adds additional check if the file is readable while checking if it's valid. This prevents loading a file that is locked due to pending copy etc. 
Currently, an FFmpeg exception would be thrown, and even though it is handled gracefully, `202` is returned, making clients unaware of the failure. After the fix, `404` will be returned in such cases.
> fix(ffmpeg_producer): Prevent loading unreadable files

- src/protocol/amcp/AMCPCommandsImpl.cpp
- src/shell/main.cpp
Boost 1.81 changes various constants in boost::locale to enums which is a breaking change, so we need separate code for each version.
> fix: compat with boost 1.81

- src/shell/run.sh
- tools/linux/Dockerfile
The final docker image build by the 'build in docker' process provided from the main CasparCG repo misses dependencies needed by CasparCG at runtime. 
Trying to run CasparCG in a container spawned from this image therefore doesn't work at the moment.
This pull request adds the required lib installs to the main Dockerfile to remedy that.
> Added dependencies to Dockerfile required for running CasparCG inside container

- src/CMakeLists.txt
- src/CMakeModules/Bootstrap_Windows.cmake
In VS the default project currently is ALL_BUILD which in fact will not build. This will set the current project to casparcg which is the project we would want built when hitting build solution.
Not sure if this can go withing the Boostrap Windows script, the cmake documentation seems to indicate it must go in the same directory as a project call. [https://cmake.org/cmake/help/latest/prop_dir/VS_STARTUP_PROJECT.html](https://cmake.org/cmake/help/latest/prop_dir/VS_STARTUP_PROJECT.html)
> Set casparcg project as the default

- src/CMakeLists.txt
- src/CMakeModules/Bootstrap_Linux.cmake
- src/CMakeModules/Bootstrap_Windows.cmake
- src/accelerator/CMakeLists.txt
- src/common/CMakeLists.txt
- src/core/CMakeLists.txt
- src/modules/CMakeLists.txt
- src/modules/bluefish/CMakeLists.txt
- src/modules/decklink/CMakeLists.txt
- src/modules/ffmpeg/CMakeLists.txt
- src/modules/flash/CMakeLists.txt
- src/modules/html/CMakeLists.txt
- src/modules/image/CMakeLists.txt
- src/modules/newtek/CMakeLists.txt
- src/modules/oal/CMakeLists.txt
- src/modules/screen/CMakeLists.txt
- src/protocol/CMakeLists.txt
- src/shell/CMakeLists.txt
- src/tools/CMakeLists.txt
This is in preparation for moving to the cmake target_precompile_headers and removing the custom solution here.
> Bump cmake minimim to 3.16 and move lanuage version to targets

- src/modules/decklink/CMakeLists.txt
- src/modules/decklink/consumer/config.cpp
- src/modules/decklink/consumer/config.h
- src/modules/decklink/consumer/decklink_consumer.cpp
- src/modules/decklink/consumer/frame.cpp
- src/modules/decklink/consumer/frame.h
- src/modules/decklink/consumer/monitor.cpp
- src/modules/decklink/consumer/monitor.h
- src/shell/casparcg.config
This work was sponsored by the BBC.
Testing build: https://builds.julusian.dev/casparcg/casparcg-server--pr-1493-80f8ee76b3bc43efa6a6ed78f5bdb95ec7e355c6-windows.zip
This expands upon #1433, to resolve some synchronisation issues that were observed on the output when splitting a channel up over multiple decklink outputs.
Since v11.0 of the Decklink SDK, some cards support a concept of 'playback groups'. This is currently supported by the Duo2, Quad2 and 8K Pro (I expect any newer multi-channel cards will also support it). By adding outputs to a playback group, the driver/card will ensure that they are run in sync with each other with the same playback timings used across each.  
We can use this new functionality to allow for grouping multiple ports on a card in combination with …
> feat: decklink consumer "secondary" ports

- src/core/consumer/frame_consumer.cpp
- src/core/consumer/frame_consumer.h
- src/core/producer/frame_producer.cpp
- src/core/producer/route/route_producer.cpp
- src/modules/artnet/consumer/artnet_consumer.cpp
- src/modules/artnet/consumer/artnet_consumer.h
- src/modules/bluefish/consumer/bluefish_consumer.cpp
- src/modules/bluefish/consumer/bluefish_consumer.h
- src/modules/decklink/consumer/decklink_consumer.cpp
- src/modules/decklink/consumer/decklink_consumer.h
- src/modules/ffmpeg/consumer/ffmpeg_consumer.cpp
- src/modules/ffmpeg/consumer/ffmpeg_consumer.h
- src/modules/newtek/consumer/newtek_ndi_consumer.cpp
- src/modules/newtek/consumer/newtek_ndi_consumer.h
- src/protocol/amcp/AMCPCommand.cpp
- src/protocol/amcp/AMCPCommand.h
- src/protocol/amcp/AMCPCommandQueue.cpp
- src/protocol/amcp/AMCPCommandQueue.h
- src/protocol/amcp/AMCPCommandsImpl.cpp
- src/protocol/amcp/AMCPProtocolStrategy.cpp
- src/protocol/amcp/amcp_command_context.h
- src/protocol/amcp/amcp_command_repository.cpp
- src/protocol/amcp/amcp_command_repository.h
- src/protocol/amcp/amcp_command_repository_wrapper.cpp
- src/protocol/amcp/amcp_command_repository_wrapper.h
- src/protocol/amcp/amcp_shared.h
- src/shell/server.cpp
There is some bad ownership handling of the channels. When creating amcp_command_repository it holds a copy of the pointer for each channel.
This class is not being destroyed correctly, because the main loop holds a reference for the console amcp client, causing it to not be destoyed when expected.
This then crashes because once caspar thinks it has destroyed everything, it tells cef to shutdown which causes the crash as the renderers are still active (as are all the channels, producers and consumers).
This fixes that by swapping out the root channels vector to contain the type needed by amcp_command_repository, which avoids the ownership issues
> fix: `video_channel` ownership #1511

- src/shell/casparcg.config
New config option appears to be in the wrong place in the sample config file.
> Move cache-path under html in config example.

- tools/linux/Dockerfile
For applications that are not the official docker, eg podman they do not by default search the dockerhub repository, it is better to explicity place the repository in the image name
> chore: Improve Dockerfile for non-docker applications

- src/modules/decklink/producer/decklink_producer.cpp
On 32bit platforms passing `long` to `data_t` causes ambiguity, because it doesn't map directly into any of the types held by `data_t`.
> fix: compilation on 32bit platforms

- src/shell/CMakeLists.txt
Commit e0bbb969b171c85332e77ee8b50f29b4634b7ad7 changed how casparcg is linked and launched on Linux, which caused a few problems.
It was partially reverted by ff1c0ba926c014f08e4c62af8e9c86013dd08a56 which restored how casparcg is launched, and this commit reverts the linking part.
> fix: Remove RPATH linking

- src/accelerator/ogl/image/image_kernel.cpp
- src/accelerator/ogl/image/image_kernel.h
- src/accelerator/ogl/image/image_mixer.cpp
- src/core/frame/geometry.cpp
- src/core/frame/geometry.h
- src/modules/ffmpeg/producer/av_producer.cpp
- src/modules/ffmpeg/producer/av_producer.h
- src/modules/ffmpeg/producer/ffmpeg_producer.cpp
- src/modules/ffmpeg/util/av_util.cpp
- src/modules/ffmpeg/util/av_util.h
- src/modules/image/producer/image_producer.cpp
Ported from https://github.com/nrkno/sofie-casparcg-server/pull/28 and added `HFILL` and `VFILL` modes.
Only image_producer for now. Will try to do the rest tomorrow.
> feat: support for scaling modes

- src/accelerator/CMakeLists.txt
- src/accelerator/ogl/image/image_kernel.cpp
- src/accelerator/ogl/image/image_kernel.h
- src/accelerator/ogl/image/image_mixer.cpp
- src/accelerator/ogl/image/image_mixer.h
- src/accelerator/ogl/util/matrix.cpp
- src/accelerator/ogl/util/matrix.h
- src/accelerator/ogl/util/transforms.cpp
- src/accelerator/ogl/util/transforms.h
- src/core/frame/frame_transform.cpp
- src/core/frame/frame_transform.h
- src/core/mixer/image/image_mixer.h
- src/core/mixer/mixer.cpp
- src/core/producer/stage.cpp
This adds a fair amount of complexity in calculations, but it allows for routes to preserve transforms which got broken when changing the route behaviour in 2.2. closes #1307 #1274
This finishes the work started years ago in 777b7f2
Unless anyone has any objections, I shall aim to merge this to 2.5 soon.
~~I still need to reenable/reimplement the scale_modes~~, but this is otherwise looking functional and pretty complete.
This is a slightly breaking change, as the way that crops compound now is slightly different. This should only affect routing one channel into another, where the crop values to be used on that routed frame are relative to the viewport and not the content. (This does sound wrong, could that change?) And also when routing a channel, the clip values for each layer are now …
> feat: rework mixer transforms

- src/modules/decklink/producer/decklink_producer.cpp
- src/modules/ffmpeg/producer/av_producer.cpp
ffmpeg master removed a bunch of fields that were deprecated, add `#if` version checks so casparcg compiles with ffmpeg master.
~~I just disabled a workaround for DVCPRO HD, since afaict it was fixed in ffmpeg a while ago. I put it in an `#if` version check so it can still be used for old versions of ffmpeg.~~
I have not verified that it was fixed, so I'm not sure how to proceed here...~~should I figure out how to verify that?~~ should I change the code to apply the workaround to new versions of ffmpeg too? (edit: I just applied the workaround for new versions too)
> Compile with ffmpeg master

- src/accelerator/ogl/util/device.cpp
- src/accelerator/ogl/util/texture.cpp
- src/accelerator/ogl/util/texture.h
Fix bug where depth metadata on textures from the cache didn't reflect actual depth
> Mixed bit-depth bugfix

- src/modules/ffmpeg/producer/av_producer.cpp
- src/modules/ffmpeg/util/av_util.cpp
Adds native support in ffmpeg producer for the yuv444p10 and yuv444p12 pixel formats
> ffmpeg producer native yuv444 10- and 12-bit support

- src/accelerator/StdAfx.h
- src/accelerator/ogl/util/device.cpp
- src/common/log.cpp
- src/modules/artnet/consumer/artnet_consumer.cpp
- src/protocol/amcp/AMCPCommandsImpl.cpp
- src/protocol/osc/client.cpp
- src/protocol/osc/client.h
- src/protocol/util/AsyncEventServer.cpp
- src/protocol/util/AsyncEventServer.h
- src/protocol/util/http_request.cpp
- src/shell/server.cpp
This PR migrates a couple of Boost classes and functions which have been marked deprecated since Boost 1.66 and have been removed with Boost 1.88.
* **`io_context` replaces ``io_service``:**
`io_service` has been a `typedef` to `io_context` since Boost 1.66 for backward compatibility (see https://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/reference/io_service.html). Also some of its methods have been declared deprecated (e.g. `io_service::dispatch()`, `io_service::post`). In some locations, CasparCG already has been using the replacement type `io_context`. For clarity all variables `service_...` have been renamed to `context_...`.
* **`ip::make_address()` replaces `ip::address::from_string`:**
That is an obvious one. The new method is also around since Boost 1.66 (see …
> Fixes for Boost 1.88

- src/common/memory.h
- src/modules/decklink/CMakeLists.txt
- src/modules/decklink/consumer/config.cpp
- src/modules/decklink/consumer/config.h
- src/modules/decklink/consumer/decklink_consumer.cpp
- src/modules/decklink/consumer/format_strategy.h
- src/modules/decklink/consumer/v210_strategies.cpp
- src/shell/casparcg.config
Enables users to opt-in to using yuv (v210) instead of rgba in the decklink consumer on standard 8-bit channels. This enables the maximum usage of the decklink cards output bandwidth.
> feat: decklink support for chosing yuv output i 8-bit mode

- src/modules/ffmpeg/consumer/ffmpeg_consumer.cpp
If the `frame_buffer_` gets full and we start dropping frames, the timestamps will become incorrect and the playback will speed up. This changes so the frame counter is passed along with the frame, making the timestamp correct even when frames are dropped.
> fix: ffmpeg consumer pts on frame-drop

- src/modules/decklink/CMakeLists.txt
- src/modules/decklink/consumer/config.cpp
- src/modules/decklink/consumer/config.h
- src/modules/decklink/consumer/decklink_consumer.cpp
- src/modules/decklink/consumer/vanc.cpp
- src/modules/decklink/consumer/vanc.h
- src/modules/decklink/consumer/vanc_op47_strategy.cpp
- src/modules/decklink/consumer/vanc_scte104_strategy.cpp
- src/modules/decklink/decklink_api.h
Add support for adding VANC packets to decklink frames
* Separate Vanc class that handles vanc related logic
* Strategy based approach to isolate different types of ancilliary data 
* Only support for a push based workflow atm (via amcp APPLY, se separate PR #1638 ), but should be fairly easy to extend with support for data arriving from other sources (ie. the producer/consumer-pipeline)
> Decklink consumer VANC
